

import keyMirror from 'react/lib/keyMirror';

export default keyMirror({
  REQUEST_FILTER_OPTIONS: null,
  REQUEST_SCHOOL: null,
  REQUEST_SCHOOL_ERROR: null,
  REQUEST_SCHOOL_SUCCESS: null,
  REQUEST_SEARCH: null,
  REQUEST_SEARCH_ERROR: null,
  REQUEST_SEARCH_FILTER_ERROR: null,
  REQUEST_SEARCH_FILTER_SUCCESS: null,
  REQUEST_SEARCH_LOAD_MORE: null,
  REQUEST_SEARCH_SUCCESS: null,
  RESET_SCHOOL_TIMELINE_YEAR: null,
  SELECT_SEARCH_FILTER: null,
  SELECT_SEARCH_MAP_YEAR: null,
  SELECT_SEARCH_SCHOOL: null,
  SELECT_SEARCH_TIMELINE_YEAR: null,
  SELECT_SEARCH_VIEW: null,
  UPDATE_SCHOOL_TIMELINE_YEAR: null,
});
